name: Deploy Static Python Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Passo 3: Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Passo 4: Executa os testes unitários
      - name: Run unit tests
        run: |
          python -m unittest discover

      # Passo 5: Executa o script Python para gerar o HTML
      - name: Generate HTML
        run: python app.py
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}

      # Passo 6: Faz o deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Publica o arquivo index.html na raiz